import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { Sidebar } from "@/components/sidebar/sidebar";
import { Topbar } from "@/components/topbar/topbar";
import { ModalProvider } from "@/providers/modal-provider";
import { initialProfile } from "@/lib/initial-profile";
import { Toaster } from "sonner";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { Navbar } from "@/components/mobile-nav/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const currentUser = await initialProfile();

  return (
      <html lang="en">
        <UserProvider>
          <body className={`${inter.className} transition duration-300`}>
          <ThemeProvider
              attribute="class"
              defaultTheme="light"
            >
              <Navbar user={currentUser}/>
              <ModalProvider/>
              <div className="flex w-full h-screen">
                <div className="h-full flex w-[0%] md:w-[16%] bg-neutral-200 ease-in-out dark:bg-black transition duration-300">
                  <Sidebar user={currentUser}/>
                </div>
                <div className="h-full w-full md:w-[84%]">
                  <div className="h-[10%]">
                    <Topbar/>
                  </div>
                  <div className="h-[90%] w-full">
                    {children}
                  </div>
                </div>
              </div>
              <Toaster />
            </ThemeProvider>
          </body>
        </UserProvider>

      </html>
  );
}
