import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { Sidebar } from "@/components/sidebar/sidebar";
import { Topbar } from "@/components/topbar/topbar";
import { SearchModal } from "@/components/modals/search-modal";
import { ModalProvider } from "@/providers/modal-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} transition duration-300`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
        >
           <SearchModal/>
          <div className="flex w-full h-screen">
            <div className="h-full flex w-[16%] bg-neutral-200 ease-in-out dark:bg-black transition duration-300">
              <Sidebar/>
            </div>
            <div className="h-full w-[84%]">
              <div className="h-[10%]">
                <Topbar/>
              </div>
              <div className="h-[90%] w-full">
                {children}
              </div>
            </div>
          </div>
          
        </ThemeProvider>
      </body>
    </html>
  );
}
